---
title: Jekyll
timezone: UTC
collections:
  uploads:
    title: Uploads
    output: true
  posts:
    title: posts
    output: true
email: jekyll@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: ''
twitter_username: shayna_m85
github_username: meli850607
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
